### ISSUE TITLE
Run Gitcoin Grant Campaigns

### ISSUE THREAD

**Issue by JulietEA** [commons-stack/Sept-1-Snapshot#1]
@GriffGreen commented on [Tue Sep 01 2020](https://github.com/commons-stack/iteration0/issues/129)

## 📋   Anything to add?

With this bull market, this will be a big fundraising opportunity for us and our community 

Very connected with #50 

## 🎉   Subtasks

- [ ] Update all of our current Gitcoin grants
- [ ] Make the Commons Stack Panvala Community Grant
- [ ] Make a Gitcoin Grant for TEC
- [ ] Make a Comms plan for promoting our grants

## 🤼‍♂️   Reviewer

@krrisis
